### ISSUE TITLE
No images in Zipped Word Lab instructions

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#1]
# Module: All
#### Step: 00

That you for providing an easy to access zipped copy of the the Lab Files and Instructions, I really like this idea. 
Unfortunately the Word Documents in the zipped copy of the Lab instructions do not include the images. 

Derek

**Comment by kalendelaney** [comment]
I cannot find where the zipped copy is stored.

**Comment by VitalyMCT** [comment]
> 
> 
> I cannot find where the zipped copy is stored.

@kalendelaney, it's in the GitHub Release, ex. https://github.com/MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure/releases/download/v20200824.01/lab_instructions-v20200824.01.zip for the latest one published

**Comment by kalendelaney** [comment]
I am in communication with the team that manages the files here and made them aware of the need to be able to get a word or PDF copy of the lab instructions that INCLUDE the images. Right now, they say there is no way to do that.

**Comment by kalendelaney** [comment]
I have created a document with all the lab instructions WITH IMAGES. (Even if, as reported, some are not absolutely correct images.) I have uploaded that as a zip to the lab folder.
