### ISSUE TITLE
Lab 2 - Printscreen of subnet that needs to be configured (10.2.0.0/24) is not the same as the one created before (10.1.0.0/24). This will confuse the learners.

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#10]
# Module: 02
#### Step: 03

Description of issue

![Capture](https://user-images.githubusercontent.com/40601026/90415184-053df080-e0b1-11ea-8520-8d8fc76cc69c.JPG)
Printscreen of subnet that needs to be configured (10.2.0.0/24) is not the same as the one created before (10.1.0.0/24). This will confuse the learners.

Repro steps:

1.
1.
1.

**Comment by kalendelaney** [comment]
New screenshots have been captured and will be incorporated into the lab

**Comment by kalendelaney** [comment]
It is looking now that the interface has changed and when you click the option for service endpoints, it covers up the subnet range. The new screenshot for Edit subnet reflects this, so there is no danger that the subnet range will show as different.
