### ISSUE TITLE
Module 7 - Azure UI update

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#100]
> In the blade for the database, under Settings, select Geo-Replication.

The Geo-Replication capability is now under "Data management" category instead of under "Settings".

**Comment by Johnny-5-Alive77** [comment]
pull request submitted with .md update and new image. #101

**Comment by sherzyang** [comment]
Thanks @VitalyMCT and @Johnny-5-Alive77! I've merged the PR.
