### ISSUE TITLE
Issue with Instructor Led Labs: Securing your database

### ISSUE THREAD

**Issue by AroraMunish** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#113]
# Module: Module 03
#### Step: 00

Description of issue
just found that lab instructions for lab3, as downloaded from github, have different objectives  than what are mentioned in presentations downloaded from https://learningdownloadcenter.microsoft.com/?wa=wsignin1.0.. 

The lab instructions from github have objectives:

After completing this lab, you will be able to:

1. Configure an Azure SQL Database Firewall

2. Authorize Access to Azure SQL Database with Azure Active Directory

3. Manage access to database objects

Whereas the ones mentioned in powerpoint slide no. 62  'Module3 Secure Environment' are

Instructor Led Labs: Securing your database

1. Configure an Azure SQL Database Firewall 

2. Authorize Access to Azure SQL Database with Azure Active Directory 

3. Enable Advanced Threat Detection for Azure SQL Database 

4. Configure Data Classification for Azure SQL Database 

5. Manage access to database objects

**Comment by JulianePadrao** [comment]
The fix for this issue will be included in the next release. Thank you.

**Comment by JulianePadrao** [comment]
This issue has been addressed. There were some minor updates in the slide deck also, which will be release by end of January. Thanks.
