### ISSUE TITLE
Correction on assumed existence of a VM in Lab1

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#13]
# Module: 01
#### Step: 04

The sentence "There should be an existing virtual machine in the list of resources." should be removed as the lab assumes a new trial subscription has just been created. The creation of a VM is the goal of this first lab. The same for the existing resource group in the next step.

**Comment by kalendelaney** [comment]
Fixed; removed references to existing VM and resource group.
