### ISSUE TITLE
Lab01 Creating SQL VM Validation Fails

### ISSUE THREAD

**Issue by MarkMcGinley760** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#132]
# Module: 01
#### Step: 09

Description of issue
After selecting the VM requirements to the letter in the instructions, validation fails due to a subscription error. Apparently the subscription is not valid for selecting that free version of SQL. This happens in both Cloud Slice environments and my own MSDN subscription.

Repro steps:

1. With the MSDN subscription I am able to select SQL 2017 on Windows 2016 - Gen 1, disable boot diagnostics and it validates. This does not help students with Cloud Slice though. There is a policy built in to that environment to ensure that you cannot deviate at all from the written selections, then fails to validate.
1.
1.

**Comment by JulianePadrao** [comment]
Hi Mark,

Could you please provide a screenshot with all the parameters you selected during the VM creation, and also the validation error log?

Thanks,

**Comment by JulianePadrao** [comment]
Closing this issue by now, please reopen it with the files requested if this is still an issue. Thanks.
