### ISSUE TITLE
Lab 4 - Pre-Staging task 1 and 2

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#143]
# Module: 04
#### Step: 01-02

Description of issue
Step instructions are not matching with the result in the lab environment, see screenshot below:
![image](https://user-images.githubusercontent.com/46898093/170706998-8a89ece4-1661-40ce-a6ec-bd0a676f7f6e.png)

In this case, I suggest to tell the students to search for the Resource Group and then from there access the logical server.

**Comment by JulianePadrao** [comment]
v
