### ISSUE TITLE
Lab 2 portal missing Lightening Bolt

### ISSUE THREAD

**Issue by afandrews777** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#157]
# Module: 2
#### Step: 00

Description of issue: https://portal.azure.com is a link that when clicked on will open a web page to the Azure portal on the student's computer and not in the lab client. All the other labs have a Lighten Bolt in front of the web address and so when you click on the link it opens the Azure portal in the lab client. Can this step be fixed to open the Azure portal in the lab client too? Thank you

Repro steps:

1.
1.
1.

**Comment by TesterTesterson1004** [comment]
That appears to be fixed!  :)
