### ISSUE TITLE
Lab2:  Clean up (only PostgreSQL, keep SQL Database)

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#16]
# Module: 02
#### Step: 00

The PostgreSQL Database is not need for later labs. It would be a good idea to remove it after task 3. Maybe include a note warning learners to not remove the SQL Database as it is required in later labs.

**Comment by kalendelaney** [comment]
It is safer not to remove any so there is no change of accidentally removing the SQL Database.
