### ISSUE TITLE
Lab 3: Wrong server name

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#18]
# Module: 03
#### Step: 01

1. From the lab VM Launch SQL Server Management Studio. Enter the server name
‎DP-300-SQL1, ensure that Windows Authentication is selected, and click Connect. 

==> The name of the server is LON-SQL1
My suggestion is to just ask the learner to click the "New Query" button.  At this point of the lab the connection is already established, there is no need to launch SSMS again.

**Comment by kalendelaney** [comment]
There is no Exercise 3 for Module 3. I cannot find where this step is. Please reopen the issue with more clarity as to exactly where the problem is.

**Comment by VitalyMCT** [comment]
@kalendelaney , I am not the MCT who originally opened this. However, the current location for this issue is:

Lab 4, Exercise 2, Task 1

Please note also that "regular" MCTs do not have sufficient access to reopen issues. We can only create new ones and comment on them.

**Comment by kalendelaney** [comment]
Thanks for the info Vitaly!

The content has been updated to assume that Management Studio is still open at the beginning of Exercise 3, Task 1, and at the end of the previous exercise, it is suggested that they keep SSMS open.
