### ISSUE TITLE
Lab 6: Runbook script error in file  DP300-lab-Module-6.ps1 

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#19]
# Module: 06
#### Step: 17

If you get the DP300-lab-Module-6.ps1 from GitHub then on line 3 you get - Name instead of -Name. I have also removed the 4>&1

**Comment by kalendelaney** [comment]
fixed; removed the space between - and Name
Removed 4>&1
