### ISSUE TITLE
Lab 6 no Powershell script

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#2]
# Module: 06
#### Step: 17

A Powershell script is mentioned as being in the D Drive of the VM, the file is not in the Labfiles on GitHub
"Open the DP300-Lab-Module-6.ps1 file from the D:\LabFIles\Automate Resources folder"

It is possible to type the script from the image, but a file would be better.

**Comment by Derekp20** [comment]
Here it is as a txt file (can't upload a ps1)
[DP300-Lab-Module-6.txt](https://github.com/MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure/files/4919953/DP300-Lab-Module-6.txt)

**Comment by kalendelaney** [comment]
DP300-Lab-Module-6.ps1 is now available in the Labfiles on GitHub.
