### ISSUE TITLE
Lab 1, Task 1, Step 3: Minor update to match current Azure Portal UI

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#20]
The following instruction and corresponding screen shot need to be updated, as the horizontal lines no longer exist:

> Launch the left navigation pane by clicking the horizontal lines next to Microsoft Azure in the top left of the portal.

**Comment by kalendelaney** [comment]
I am still seeing the horizontal lines in the portal.
