### ISSUE TITLE
Lab 1, Task 1, Step 4: VM does not exist

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#21]
This is the beginning of the 1st lab in the course, however, it contains the following statement:

> There should be an existing virtual machine in the list of resources. 

I think this is an error in instructions. If not, how does the VM get into the student's Azure Pass subscription?

Similarly for the next step in this task (Step 5)

**Comment by kalendelaney** [comment]
This was a duplicated of a previously reported issue; that issue has been fixed so this one will also be closed.
