### ISSUE TITLE
References to "case study"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#24]
This is referred to in Lab 3, 4 and 6. Example:

>The students will take the information gained in the lessons and from the **case study** to configure and subsequently implement security in the Azure Portal and within the AdventureWorks database. 

However, this course does not have a case study.

**Comment by kalendelaney** [comment]
Fixed; removed reference to 'case study'
