### ISSUE TITLE
Lab 3 structure and timing

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#25]
Two issues, which may be related:

1. The suggested overall timing for the lab is 60 minutes. However, it has 1 exercise only and that exercise is budgeted at 30 minutes.

2. There may be a mix-up between exercise and task levels in this lab's structure. The first bullet point is exercise and the rest are tasks. Yet they seem to belong at the same level.

**Comment by kalendelaney** [comment]
Cleaned up the task vs exercise confusion. All tasks are now exercises and total for all exercises is 60 minutes.
