### ISSUE TITLE
Screenshot does not match instructions

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#26]
# Module: 00
#### Step: 3

Description:

> In the detail screen for your SQL server, move your mouse to right of the server name, and click copy to clipboard button as shown below.

Screenshot:

![image](https://user-images.githubusercontent.com/1765732/92521099-a587c080-f1ea-11ea-9468-9d249d79286c.png)

**Comment by kalendelaney** [comment]
New screenshot has been captured and will be incorporated into lab.

**Comment by kalendelaney** [comment]
The screenshot has been updated in the lab.
