### ISSUE TITLE
Lab 3 - Extend pre-requisites

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#27]
Current pre-requisites statement:

> An Azure SQL server you created in the lab for Module 2. Azure Active Directory access in the subscription. 

Later in the lab:

> You will be prompted to create a storage account. Choose the storage account you created in **Lab 1**.

**Comment by kalendelaney** [comment]
fixed, added storage account to prereqs
