### ISSUE TITLE
Lab 4 - References to AdventureWorks2017

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#30]
The instructions for this lab reference this database. However, the database previously created in Lab 2 is called "AdventureWorks" (i.e. without "2017" suffix).

There are also many additional references to the same database later on:

![image](https://user-images.githubusercontent.com/1765732/92639637-1cd05980-f2aa-11ea-9aba-ea6e2014fd6a.png)

**Comment by kalendelaney** [comment]
AdventureWorks is the Azure SQL Database. AdventureWorks2017 is the on-prem database on the Lab VM LON-SQL1.
No changes.
