### ISSUE TITLE
Lab 7 - Resource group name

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#31]
> Your storage account name must be unique and all lower case with no special characters. You should change dp300storage in the above to a unique name like dp300storagemsl123. The value dp300lab06 is the name of a Resource Group. Make sure you use one that has been created in an earlier lab.

This description follows this command:

> az storage account create -n dp300storage -g DP-300-Lab02 --kind StorageV2 -l eastus2

So the two statements are inconsistent. I believe the resource group is correct in the command and incorrect in the description.

**Comment by kalendelaney** [comment]
Which Exercise and step?

**Comment by VitalyMCT** [comment]
Exercise 2, Task 1, Step 8

**Comment by kalendelaney** [comment]
This has been fixed.
