### ISSUE TITLE
Lab 7 - References to Module 3

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#32]
> **Pre-requisites**: The Azure SQL Database used by Exercise 1 was created in the lab for Module 3. 

and 

> The Students will alter the configuration of the Azure SQL Database created during the lab for Module 3 to make it highly available.

The Azure SQL Database was in fact created in Lab 2

Likewise for references to "Lab 3". Example (there may be more instances):

> Click on the Azure SQL Database that was created in Lab 3. An example is shown below.

**Comment by kalendelaney** [comment]
AdventureWorksLT was created in Lab 2 through the Portal. AdventureWorks was created in Lab 3 by importing a .bacpac file.
