### ISSUE TITLE
Lab 7 - WideWorldImporters vs. AdventureWorks

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#33]
~~It seems the former is used instead of the latter. There have been no references to the former in any other labs.~~

I now understand there are two unrelated databases involved in this lab: Azure SQL Database from Lab 2 and a local SQL Server database. 

Perhaps this fact can be made clearer to the students. The introduction of the WideWorldImporters on the local lab VM is especially important to highlight, I think.

**Comment by kalendelaney** [comment]
Perhaps also the instructor could mention this to the students as a lead in to the lab?
