### ISSUE TITLE
Lab 7 - New database server

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#34]
> On the New server blade, enter a name of module7geo,, a valid admin login, and a secure password.

1. We should instruct the students to create a globally unique server name
2. There is an extra comma after the server name prefix

Also, and this is a suggestion only - it would probably make sense to add a cleanup step to the end of the lab. This new database server is fairly expensive and many students want to use their Azure Passes after the course.

**Comment by kalendelaney** [comment]
Added info about making servername unique and removed comma. Suggestion to clean up everything could be made by the instructor.
