### ISSUE TITLE
Lab 7 - Exercise 1 fails with Azure error

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#35]
Getting the following:

![image](https://user-images.githubusercontent.com/1765732/92644161-e64a0d00-f2b0-11ea-813f-535c53c1a596.png)

Nothing useful in Event Log.

Can someone repro this?

**Comment by kalendelaney** [comment]
I cannot repro this. Can you?  I will close, and reopen if we hear from others that it is failing.
