### ISSUE TITLE
Lab 7 - Exercise 2 - Task 1 - Instruction to use RDP

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#36]
> Switch to the Remote Desktop session for LON-SQL1.

I don't think this is needed. Students use ALHs to access this machine. ALHs use their own connectivity mechanisms.

**Comment by ilikesql** [comment]
Not in all environments, @kalendelaney please revise lab instructions to update to "switch context to, making it less independent of environment and ALH specific

**Comment by kalendelaney** [comment]
Changed to "Verify that your context is the LON-SQL1 Virtual Machine."
