### ISSUE TITLE
Lab 7 - Formatting for storage account keys command

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#37]
> az storage account keys list -g DP-300-Lab02 -n dp300storage

This command needs to be formatted like the other AZ CLI commands in GitHub Markdown. Otherwise it does not render properly in GitHub and in ALH interfaces.

**Comment by kalendelaney** [comment]
This has been reformatted.
