### ISSUE TITLE
Missing Image in Lab 1 Task 3

### ISSUE THREAD

**Issue by sqlgeekster** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#4]
# Module: 1
#### Step: 1

Description of issue
The image is not showing up when displaying the markdown on Github.  

Repro steps:

1.
1.
1.

**Comment by kalendelaney** [comment]
I cannot find what image this is referring to. Lab 1, exercise 1 does not have a Task 3.  The only Task 3 in this lab correctly shows an image. Please be more specific as to where you are encountering this error.  Thanks
