### ISSUE TITLE
Lab 6 - Prerequisites

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#41]
Regarding

>Pre-requisites: A SQL login in the Azure database AdventureWorks has been created for maintenance purposes

Can this please be reworded in terms of labs done in this course, similarly to the way previous lab prerequisites are? 

It seems the prerequisite for this lab is completion of (at least part of) Lab 2

**Comment by kalendelaney** [comment]
This is created in the lab. The prereq line has been removed.
