### ISSUE TITLE
Lab 6 - Quickstart template usage

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#42]
>In the Resource Group field, click “Create New” and type DP300-Lab06. In the SQL Administrator login field, type labadmin. For the password field, type the password Azur3Pa$$. Click on the check box next to “I agree to the terms and conditions” and then click purchase. 

After entering the password one must click the "Review + create" button.

Also, there is no longer a checkbox as described in that last sentence. One just clicks "Create" on the last screen to finalize provisioning.

**Comment by kalendelaney** [comment]
This have been fixed.
