### ISSUE TITLE
Lab 6 - Notification email

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#43]
> Select Email/SMS message/Push/Voice and enter the name DemoLab. In the flyout screen on the right, click the check box next to email and click OK. Then click on the Review and Create button, and then click Create on the Create Action group screen.

Before clicking OK one must enter an email address (required field).

**Comment by kalendelaney** [comment]
Fixed
