### ISSUE TITLE
Lab 6 - Automation account provisioning

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#44]
A couple of issues:

> Name: DP3006Lab06

There is a typo in the name. It should say DP300Lab06. The screenshot is correct.

> Resource Group: Use the resource group you created in Lab 2. DP300-Lab02

In the screenshot the RG is "DP300-Lab06". Which one is correct?

**Comment by kalendelaney** [comment]
The name is DP300Lab06.  The Resource group is DP300-Lab06. Corrections have been made and new screenshot inserted.
