### ISSUE TITLE
Lab 6 - Cannot connect with Query Editor

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#45]
Running into a bit of a strange issue with the last exercise. Access to Azure services is allowed and local client IP is added in firewall. However, connection fails and IP address used is 166.172.121.44. 

It is not an address in the latest Azure IP address block published at https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519 (and updated this week).

It looks like Azure may be using an unpublished IP address with Query Editor and it's that address that should be added to the firewall. It may be an Azure bug. Regardless, the instructions around this do not currently work as written, at least for me.

Ideas?

![image](https://user-images.githubusercontent.com/1765732/93670634-c82b9c00-fa6a-11ea-9e53-87d4ad72132f.png)

**Comment by kalendelaney** [comment]
I have been unable to reproduce this error. If it persists you'll need to contact Azure support.
