### ISSUE TITLE
Lab 4 - Stopping extended events session

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#48]
> Right click the Extended Events session and select Stop Session. 

I think it will be useful to give students some more guidance on finding this option in the SSMS UI. 

The intent appears to be to have them right-click on the "Blocking" menu.

**Comment by kalendelaney** [comment]
elaborated on the name of the session to be stopped
