### ISSUE TITLE
Lab 4 - Shortcut to run query

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#49]
> Click the execute button or **press t** to execute this query. 

I think this was meant to say **Ctrl+T**.

**Comment by kalendelaney** [comment]
No, all the instructions used to say 'or press the F5 key' and when we removed that, a stub remained in Exercise 2, Task 2, Step 2. Stub was removed.
