### ISSUE TITLE
Lab 4 - Missing code

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#50]
This step references code that does not exist in it:

![image](https://user-images.githubusercontent.com/1765732/93713953-5b2d0a80-fb2d-11ea-9ad7-ff792e93e4a8.png)

**Comment by kalendelaney** [comment]
The code was in Step 2. Step 1 was edited to remove the reference.
