### ISSUE TITLE
Lab 4 - Reference to index fragmentation report query

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#51]
> Re-execute the query from **step 3** in Task 1. Confirm that the AK_Address_StateProvinceID index no longer has fragmentation greater than 50%. 

The query that students need to run here is in Step 2. Step 3 contains a different query.

**Comment by kalendelaney** [comment]
Should have been stated that this was exercise 3. 
In Task 2, changed the references in steps 3 and 4.
