### ISSUE TITLE
Lab 4 - Screenshot issue

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#52]
There are two logical reads in this exercise:

- 134 before rebuild
- 70 after the rebuild

However, the screenshot before rebuild in instructions shows the after rebuild count, which is confusing. Suggest either removing the image or putting matching counts in the corresponding locations.

![image](https://user-images.githubusercontent.com/1765732/93714061-105fc280-fb2e-11ea-9c14-1a6e49d917b5.png)

**Comment by kalendelaney** [comment]
Screen shot regenerated, but I got a different number before the rebuild.  However, 70 was the number from after, so I have replaced the screen shot.
