### ISSUE TITLE
Lab 5 - Redundant query windows

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#54]
In Exercise 1, Task 1, Step 1 we create a new query. Then in Step 3 we create another query. The query window created in Step 1 is never used.

I think the following should be removed from Step 3:

> Start a new query by clicking the New Query button in SQL Server Management Studio.

**Comment by kalendelaney** [comment]
done.
