### ISSUE TITLE
Lab 5 - Missing screenshot

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#55]
> Copy and paste the code below into a new query window. Click on Include Actual Execution Plan icon **as shown below** before running the query, or type CTRL+M.

A screen shot is referenced, however, it's not present.

**Comment by kalendelaney** [comment]
There are many places in the lab where it says "as shown below". It would be helpful to post the Exercise, Task and Step. 

In Exercise 2, Task 2, Step 1, "as shown below" has been removed. An earlier screenshot showed where the icon was located.
