### ISSUE TITLE
Lab 5 - Executing workload for Query Store exercise

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#56]
> Navigate **back** to the D:\Labfiles\Query Performance\ExecuteRandomWorkload.sql script to execute a workload.

Unless there is a step missing, this is the 1st time this script is referenced. So the "back" word should be removed.

There is something strange about this step in general. As written, we are instructed to run the same script twice consecutively. Is this intentional? If so, for what reason?

**Comment by kalendelaney** [comment]
Removed the word 'back'. 

There are many reasons a script might be run twice. It may be done to make sure all reads are only logical and the costs of physical reads are not affecting the costs. It could be just to give the system more data to work with.  No additional changes made.
