### ISSUE TITLE
Lab 5 - Object explorer

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#57]
> In order to view the Query Store you will need to refresh the AdventureWorks2017 database in Management Studio. Right click on database name and choose click refresh. You will then see the Query Store option under the database.

The way the instructions are currently structured, the Object Explorer is not connected to any servers. Only the query window is. So this instruction cannot be followed as written. Need to adjust accordingly.

**Comment by kalendelaney** [comment]
Added "Make sure that Management Studio is connected to the local SQL Server instance."
