### ISSUE TITLE
Lab 1 - Boot diagnostics storage account during VM provisioning

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#58]
> Make note of the storage account name you are creating here, you will use it in subsequent labs. Verify that "Enable auto_shutdown" is off.

Azure functionality has changed here recently and the students should switch from the 1st option under Boot Diagnostics to the 2nd one to retain previous functionality. Or they can keep default here and create storage account later.

This change was just released yesterday:

https://www.hametbenoit.info/2020/09/22/azure-you-can-now-use-a-managed-storage-account-for-the-vm-boot-diagnostics/

New functionality:

![image](https://user-images.githubusercontent.com/1765732/94021175-ba835880-fd81-11ea-9dcf-6deabcd1e0af.png)

**Comment by kalendelaney** [comment]
We are in process of updating the instructions to account for this change.

**Comment by kalendelaney** [comment]
update: Lab 3 has been rewritten to create a new storage account and not use the one created here in Lab 1  Lab 1 will be updated shortly. For now, with the new lab 3, it won't matter which option students choose.

**Comment by kalendelaney** [comment]
Fixed with new screenshot.
