### ISSUE TITLE
"Add Firewall rule" section should be more distinct. 

### ISSUE THREAD

**Issue by DrEnnui** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#6]
# Module: 02
#### Step: 05

Description of issue:
The section which begins, "If you are asked to add firewall rule ..." probably should be separated and it's circumstantial nature highlighted.  I've had students who would get stuck at a step like this, wondering why they aren't being asked to add that rule.

Repro steps:

1.
1.
1.

**Comment by kalendelaney** [comment]
I turned  the description of adding the firewall rule into a note and called out that it was conditional. .
