### ISSUE TITLE
Lab 03 Ex 03 - Azure renaming

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#60]
Due to renaming on the Azure portal some of the instructions in Lab 3 Exercise 3 are incorrect.

Server level:
**Advanced Data Security** has been renamed to **Security center** as the option under Security.  This leads to the same page although the heading has changed from **Advanced Data Security** to **Azure Defender for SQL**.

Database level:
Again the name has changed from **Advanced Data Security** has been renamed to **Security center** as the option under Security.  The **Data Discovery & Classification** chart has been removed from the resulting page.  Data Discovery & Classification is an option under the security group.

Need to update the steps and screenshots for the lab to reduce confusion for the delegates.

![Server-Level](https://user-images.githubusercontent.com/36226388/96588109-1edefc80-12db-11eb-8326-b8eb2de0986e.png)
![Database-Level](https://user-images.githubusercontent.com/36226388/96588112-20102980-12db-11eb-8ced-cd4daf5a3efe.png)

**Comment by VitalyMCT** [comment]
@kalendelaney, the PR that was intended to address this failed due to merge conflicts. Can you please review?

**Comment by kalendelaney** [comment]
I'm trying to resolve the conflicts but it's unclear exactly what it should say and where the new screenshots are. I don't have time to completely run the lab right now.  I see the images above, but they look like your own images and include resources that the students would not see in the lab. The screenshot has to be exactly what the student would see.  Thanks
