### ISSUE TITLE
Lab 6 - Structure and timing

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#63]
This is very similar to #25 and #29 

Lab 6 has 3 exercises marked at 30 minutes each. Yet the total duration of Lab 6 is noted as 60 minutes. Either the exercise or the total duration should be adjusted to be in sync.

Additionally, the structure of the Exercises and Tasks does not correspond to the description within the Exercises. The nesting of Exercises and Tasks should be adjusted to match the description (or vice versa).

**Comment by kalendelaney** [comment]
Timings have been adjusted. I also made some changes to the Exercises and Task descriptions but I'm not sure I got exactly what the problem was. Please verify.

**Comment by VitalyMCT** [comment]
Reviewing it now. Lab timing is now matching exercises, so that's great. 

One thing I think still needs to be adjusted is to have the overall lab objectives match the combined exercise objectives. I've highlighted the lab objectives that are not in exercises (or worded differently there?) below:

**Schedule maintenance jobs and configure notifications**
**Configure multi-server automation**
**Configure performance metric related notifications**
**Configure notifications based on resources**

**Comment by kalendelaney** [comment]
The only thing I see missing is the multi-server automation. We schedule maintenance jobs and notifications with the Runbook, we configure notifications based on the cpu performance metric. Actually, notifications based on resources is really the same thing as the performance  metric notifications, so we can get rid of one of those. I will also rearrange the order to match the order the objectives show up in the exercises.
