### ISSUE TITLE
Lab 7 - Exercise 1 sections

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#64]
It looks like some sections in this Exercise accidentally got duplicated from the Lab level. Example:

![image](https://user-images.githubusercontent.com/1765732/100477201-7face200-309c-11eb-8414-195682d1f70c.png)

Also, some sections that are present for Exercises elsewhere are missing. Example: Recommended timing.

Please review this Exercise to make it consistent with others.

**Comment by kalendelaney** [comment]
This lab has been updated.
