### ISSUE TITLE
Lab 3 - Azure AD Admin Limitations

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#65]
Regarding the following:

>A Microsoft account (a user account from Outlook, Gmail, Hotmail or Yahoo, for example) is not supported for the Azure Active Directory administrator for Azure SQL Database. As a workaround, you can create an Azure Active Directory group named DBA and add your user account to it. Alternatively, you can skip Exercise 2.

Students are typically doing this course with throw-away Microsoft accounts activated using the Microsoft Learning Azure Pass process. I think we should make it easier to follow the instructions for this lab using this mainline scenario.

Two alternative options I would like to propose:

1. Remove Exercise 2 from the lab
2. Provide additional instructions that cover creating the DBA group in AAD

**Comment by kalendelaney** [comment]
I think the instructions are complete enough for now. If an instructor does not know how to create an AAD group, they can just tell the students to skip exercise 2.

**Comment by VitalyMCT** [comment]
> I think the instructions are complete enough for now.

The students in my recent DP-300 classes would disagree. Clearly there is a gap here, in that the instructions in this one particular area are insufficiently detailed for the target audience (students, not MCTs). 

Hence suggestion #2 to close the gap and make students happy.
