### ISSUE TITLE
Please add instructor demo details

### ISSUE THREAD

**Issue by RuggieroLauria** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#66]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by kalendelaney** [comment]
Can you provide more details?

**Comment by RuggieroLauria** [comment]
I cannot find the trainer demo steps. Is a bit complicate to deliver demos

Ruggiero Lauria

MCT MCITP MCSE MCSA

Data Scientist
Windows and SQL Server Administrator

http://ruggierolauria.blogspot.com

Il gio 21 gen 2021, 22:32 KALEN DELANEY <notifications@github.com> ha
scritto:

**Comment by kalendelaney** [comment]
There are no specific demos prepared for this course. If you know the subject matter well, you can choose to demonstrate whatever you feel is appropriate.
