### ISSUE TITLE
Azure SQL - Connectivity Methods Updated

### ISSUE THREAD

**Issue by strugdt** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#69]
# Module: 02
#### Step: 06

Description of issue

Azure portal has been updated. New screenshot is shown below - 

![image](https://user-images.githubusercontent.com/16652407/111140998-f1625a80-85bd-11eb-9e9f-2a625f50dbd5.png)

Old screenshot - 

![image](https://user-images.githubusercontent.com/16652407/111141029-fcb58600-85bd-11eb-9725-ac7c6833e5d8.png)

**Comment by sherzyang** [comment]
Thanks @strugdt! I pushed an update to reflect the UI change. The UI has changed again since your screenshot, so the instructions reflect the latest experience.
