### ISSUE TITLE
Instructions contain specific username

### ISSUE THREAD

**Issue by DrEnnui** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#7]
# Module: 02
#### Step: 03

Description of issue:  Students are told to connect to the PostgreSQL database using a specific username, when they were told to create their own username when creating that database in the previous task.

Repro steps:

1.
1.
1.

**Comment by kalendelaney** [comment]
I'm not seeing anyplace where you are told to create your own username. Can you please point to the Task and Step where that happens?

You are asked to create your own servername, but not username.

**Comment by DrEnnui** [comment]
<img width="1213" alt="Screen Shot 2020-08-12 at 12 21 40 PM" src="https://user-images.githubusercontent.com/34311607/90058489-a59daa80-dc96-11ea-84db-e5a5c560fa3f.png">

**Comment by kalendelaney** [comment]
Thanks for your quick reply. However, this doesn't show me where you are asked to CREATE your own username.  That's what I was asking for.

**Comment by DrEnnui** [comment]
I see that now.  I should have been referring to the servername instead of the username (which is the fixed value of dp300admin).

The user name used to connect to the Postgre server incorporates the servername "created" in Exercise 4, Task 1, step 5, which required that the student's initials be incorporated into the servername to ensure global name uniqueness. 

However, I now see that there is a note to the student about using your own suffix.  I don't recall seeing that note earlier, but it is a sufficient reminder that the hostname needs to be customized, and resolves my initial concern.  I might suggest also using **"dp300admin@_dp300-lab02-***<your initials>"_** as the suggested connecting user name as an additional reminder that the students should be using their customized servername.

**Comment by kalendelaney** [comment]
You're seeing the note because I just added it.

**Comment by DrEnnui** [comment]
Lol.  Thanks for telling me, otherwise it would be quite embarrassing for an instructor to fall into the same trap that they were attempting to help students avoid!
