### ISSUE TITLE
Duplicate Slide and Typos

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#73]
# Module: 01

Slides 44 and 47 appear to be identical. Should one be removed?

Slide 50 - "Azure review features", however the notes and the rest of the lesson talk about "preview" features.

**Comment by shannonlindsay** [comment]
Thanks @boomalator - both of these items have been fixed. Updated slides will appear in the MCTDLC on 5/14. Thank you!
