### ISSUE TITLE
Review question contradicts content

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#74]
# Module: 01

Slide 26:
![image](https://user-images.githubusercontent.com/17992669/114343375-f7931a80-9b1a-11eb-8a89-e8d91bb01953.png)

Slide 41:
![image](https://user-images.githubusercontent.com/17992669/114343430-14c7e900-9b1b-11eb-9138-35185f7f27b6.png)

**Comment by shannonlindsay** [comment]
Thanks @boomalator - the wording on slide 26 has been revised. You will see the slide updated in the MCTDLC on 5/14. Thanks for flagging!
