### ISSUE TITLE
SQL is war. (Typo)

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#75]
# Module: 1
#### Slide 44

I guess war would be "combatibility level" so this must relate to how unruly my hair is --- it's comb-ability? :)

![image](https://user-images.githubusercontent.com/17992669/114343681-a6375b00-9b1b-11eb-8c66-cd21532866d4.png)

**Comment by boomalator** [comment]
Also, this slide appears to be present as #44 and #47 in my copy, with only minor wording changes.

**Comment by shannonlindsay** [comment]
Thanks @boomalator - both of these issue have been fixed. You'll see these updated in the 5/14 release available in the MCTDLC.
