### ISSUE TITLE
Lab 4 Ex 2 task1 Not able to login as LON-SQL1

### ISSUE THREAD

**Issue by hassamirfan** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#76]
# Lab/Demo: 4
##Exercise: 2
#### Step: 02

Description of issue:Not able to login as LON-SQL1
 It doesnt connect and gives the following error:::

TITLE: Connect to Server
------------------------------

Cannot connect to LON-SQL1.

------------------------------
ADDITIONAL INFORMATION:

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) (Microsoft SQL Server, Error: 53)

For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&EvtSrc=MSSQLServer&EvtID=53&LinkId=20476

------------------------------

The network path was not found

------------------------------
BUTTONS:

OK
------------------------------

**Comment by sherzyang** [comment]
Hi @hassamirfan, it looks like the issue you experienced is not ongoing. If you try the exercise again, it should work. You may want to check if you've downloaded the files after logging in, before going to the main lab instructions page. 
<img width="278" alt="lab04-download-example" src="https://user-images.githubusercontent.com/19577448/119544992-240b9a80-bd47-11eb-9c72-4bc239fc4f68.png">

I'll close this issue, if you're still experiencing the problem we can open another issue. Thanks!
