### ISSUE TITLE
Grammar Error - Least privilege

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#77]
# Module: 03
#### Slide 29

"Then" should likely be "than".

![image](https://user-images.githubusercontent.com/17992669/114494764-22907380-9bda-11eb-9936-6c18c1395b30.png)

**Comment by shannonlindsay** [comment]
Thanks for pointing this out @boomalator - you will see the slides updated in the MCTDLC on 5/14. Thank you!
