### ISSUE TITLE
Confusing sentence - Data Classification

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#78]
# Module: 03
#### Slide: 56

This sentence is confusing, even to accomplished English speakers:

![image](https://user-images.githubusercontent.com/17992669/114495692-c29acc80-9bdb-11eb-8b95-9e615ae95aad.png)

1. I think "included in any requests to be forgotten" means that if a person makes a request to be forgotten under GDPR, all data tagged as GDPR *must* be covered by the request. However, I suspect that morally, if not legally, a request to be forgotten should include *all* data unless there is a legal justification or requirement for it to be retained. (And if that's not what the phrase meant then I don't know what the author is trying to say).

2.  I think "any requests by EU customer data requests" is a typo or error... a "customer" makes requests. A "customer data request" does not make requests.

3. Doesn't it depend what said EU customer is requesting? If the customer is requesting data that didn't happen to be tagged GDPR, why would you exclude it, if the customer is entitled to it? Just because customer X lives in Copenhagen, doesn't mean that data "marked as GDPR" should automatically be returned, if, say, that data represents customer Y (regardless of whether or not customer Y is in the EU, or the data is marked GDPR, it shouldn't be going to customer X).

However, I am not a GDPR expert, by any means. So, perhaps if using GDPR as an example, enough context should be provided so that non-EU students (and instructors) can understand the example.

**Comment by shannonlindsay** [comment]
Thanks @boomalator - this has been revised to simply say, "Data that is marked as GDPR should be included in any requests to be forgotten" meaning that any data including PII should be found and erased systematically. I hope that clears it up! You will see the slides updated in the MCTDLC on 5/14. Thank you!
