### ISSUE TITLE
Typography incorrect - Quotes and Hyphens

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#79]
# Module: 03
#### Slide

Capitalization of Shipcity/ShipCity would make the C# fail compilation.
Last line of c# should not contain curly quotes (single or double)
User input should contain two hyphens, not one en-dash
First line of Executed SQL should not have a curly quote after Redmond

I'd note that SQL Injection has been well described and railed against for (at least) 15 years and yet remains on the OWASP top ten list. Still. (Sigh.)  

![image](https://user-images.githubusercontent.com/17992669/114496558-70f34180-9bdd-11eb-9b85-d6f38e16fafd.png)

**Comment by shannonlindsay** [comment]
Thanks @boomalator - these changes have been made. You will see the slides updated in the MCTDLC on 5/14.
