### ISSUE TITLE
GP Gen4 not available in all regions

### ISSUE THREAD

**Issue by DrEnnui** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#8]
# Module: 03
#### Step: 09

Description of issue:
My import failed when using Service Objective GP_Gen_4_2, with the error message indicating that Generation 4 was not available in my region (US West 2).  My attempt with Gen_5_2 was successful.

<img width="1309" alt="Gen4Error" src="https://user-images.githubusercontent.com/34311607/87581632-1ba9f400-c68e-11ea-8fa0-3876fbb5d3a2.png">

Repro steps:

1.
1.
1.

**Comment by kalendelaney** [comment]
Lab instructions have been updated to indicate that GP-Gen5_2 should be used.
