### ISSUE TITLE
Lab 1 - Very minor Azure UI change during cleanup step

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#83]
> Navigate to the main (Overview) blade for the dp300sqlvmlab01 Virtual Machine and click the delete button in the menu.
> Click Yes.

The confirmation prompt now has "OK" instead:

![image](https://user-images.githubusercontent.com/1765732/114602939-00cfd480-9c4c-11eb-91f4-cc41c605463b.png)

**Comment by sherzyang** [comment]
Thanks @VitalyMCT just pushed a change to address the update.
