### ISSUE TITLE
Lab 2 - Azure UI change - Security tab added to SQL Database provisioning

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#85]
> Confirm the endpoint appears on the Networking page, and then click the Next: Additional settings button.

The Security tab is now between Networking and Additional Settings, so the instructions need to be amended accordingly.

Also, the following is no longer applicable on the Additional Settings tab, as it's been moved to Security tab:

> Ensure enable advanced data security is set to Not now

**Comment by sherzyang** [comment]
Thanks @VitalyMCT! I've pushed an update to address the UI change.
