### ISSUE TITLE
Demo requested no longer compiles & slide is wrong.

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#86]
# Module: 04
#### Step: All

Slide 61 

Repro steps: Attempt to compile and/or use the sample app decribed as "level 100-200". Because it is a five year old sample, it is using deprecated frameworks and will not compile. Retargetting to a current framework doesn't fix it (nuget updates fail). The sql version might still work; however for the audience at hand, the "simpler" version would have been better.

In addition the slide says to "build an Azure SQL database", but the demo "instructions" suggest using a SQL Server/VM not a constrained Azure DB.

See also microsoft/sql-server-samples#927

![image](https://user-images.githubusercontent.com/17992669/114659961-b8e39880-9cb1-11eb-9019-d5c0f4f0a8c8.png)

**Comment by shannonlindsay** [comment]
Thanks @boomalator - we've removed this slide/demo for the moment and will reassess for the next major course update. You will see the slides updated in the MCTDLC on 5/14. Thank you!
