### ISSUE TITLE
Typo - Module 5

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#87]
# Module: 05
#### Step: 00

![image](https://user-images.githubusercontent.com/17992669/114662486-fe09c980-9cb5-11eb-9812-4f36156915f9.png)

Leaving aside that I doubt this is the "most important thing" I can do in life, or even in SQL, and that most DBAs aren't the coders, the last "you" should be "your". I would also add a "the" and a "that".

**Comment by sherzyang** [comment]
@boomalator thanks for catching that. I've made a change. We will publish a batch of slide changes hopefully by next week.
