### ISSUE TITLE
Typo - Module 5, Slide 40

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#88]
scan*ned*

![image](https://user-images.githubusercontent.com/17992669/114663030-e41cb680-9cb6-11eb-88f7-f96258436415.png)

**Comment by shannonlindsay** [comment]
Thanks @boomalator - got it. This will be included with the updated slides being released at the end of this week, 5/14.
