### ISSUE TITLE
Bad instruction sequence

### ISSUE THREAD

**Issue by DrEnnui** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#9]
# Module: 03
#### Step: 09

Description of issue:
The text instructing the student to "Replace 192.168.1.1. with your client IP address..." should <i>probably</i> be placed before the instruction to run the query.

Likewise, ensuring that we are using the correct database should probably be done before we apply that firewall rule.

Repro steps:

1.
1.
1.

**Comment by kalendelaney** [comment]
It looks like this should be Step 12, not Step 09
I moved the line about replacing the IP address. 
As for making sure we’re in the right database before adding the firewall, that is addressed in the previous step. In step 12, we are just confirming that we are still in AdventureWorks.

**Comment by DrEnnui** [comment]
Thanks!
