### ISSUE TITLE
Lab 5, Exercise 4, Task 1 - Bullet point issue

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#90]
The bullet points after the first one do not use numbering:

![image](https://user-images.githubusercontent.com/1765732/114813551-33babb00-9d67-11eb-8860-8249bb5156d9.png)

**Comment by sherzyang** [comment]
Thanks @VitalyMCT! I've just pushed a change to resolve this issue.
