### ISSUE TITLE
Azure UI Change - Automation Accounts

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#91]
# Module: 06
#### Step: 2

Azure UI now says "create", not "add".

![image](https://user-images.githubusercontent.com/17992669/114907073-ee82a180-9dd7-11eb-9d2e-6461f4d24835.png)

**Comment by sherzyang** [comment]
Thanks @boomalator, I've pushed an update.
