### ISSUE TITLE
Azure Steps Changed - Adding Client to firewall

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#92]
# Module: 06
#### Step: 06

Adding the client IP to the firewall to access Query Editor has been (vastly and well) simplified to one step, now called "whitelist" (how'd that get past the socially-aware editors?) and does not require going into the firewall settings. One click. Lab instructions should be updated.

![image](https://user-images.githubusercontent.com/17992669/114908233-22aa9200-9dd9-11eb-95e3-a8d084def1cf.png)

**Comment by sherzyang** [comment]
Thanks @boomalator, I've pushed changes to address the change in firewall access and step numbers.
