### ISSUE TITLE
Use of "blade" throughout labs

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#93]
"Blade" is not a term found in the UI, nor, to my knowledge, in Azure official documentation. I believe it is a hold over from very early styling of Azure UI's where "blades" looked like, well... blades. I believe it's use is elitist and that it is primarily used by those who have been involved with Azure for a long time. In my opinion, it is, at best, Jargon.

Aside from style issues, it is unknown to most students. This course is often the first significant exposure to Azure for a dba coming from an on-prem environment or having only accessed cloud resources in a tool like SSMS. Many students ask "what's a blade?"

As such I think the term "blade" should be avoided (rather using "page", "window", "pane", "section", etc.).
If "blade" is to remain the "official" term, then all introductory Azure courses, including this one, should explain what it means, and which UI elements are a "blade" and which are just a "page".

**Comment by olaekdahl** [comment]
It is an official term, see https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/blade and https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui. But I agree, it's unfamiliar to a lot of students.

**Comment by sherzyang** [comment]
@boomalator @olaekdahl thanks for sharing the student perspective that this term causes confusion. I will take that feedback back to my team.
