### ISSUE TITLE
Lab Navigation Incorrect - Schedule for Runbook

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#95]
# Module: 06
#### Step: 20

After publishing the runbook in step 19, you are left in the runbook details page. The "Schedules" on this nav menu are specific to this runbook and are not the "shared resources" schedules.  When clicking "Add a schedule", this intermediate page appears, and students must click "Link a schedule to your runbook"

![image](https://user-images.githubusercontent.com/17992669/114914229-4d97e480-9ddf-11eb-8ae2-4d3e451e4525.png)

**Comment by sherzyang** [comment]
Thanks @boomalator, I added a screenshot at the step.
