### ISSUE TITLE
Azure UI change - Schedules

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#96]
# Module: 06
#### Step: 022

While half the time Azure changes "Add" to Create, on this page, they have changed "Create" to "Add". Sigh.

**Comment by boomalator** [comment]
Oops... the correct screenshot from the flow in the lab (also "Add") --

![image](https://user-images.githubusercontent.com/17992669/114914724-e6c6fb00-9ddf-11eb-8246-c7797aca6b9f.png)

**Comment by sherzyang** [comment]
Thanks @boomalator! I've pushed a change with the screenshot you provided.
